// Auto-generated by deploy-anvil.sh — do not edit ANVIL section manually
// Sepolia section updated automatically by deploy-sepolia.sh

export interface ChainAddresses {
  MockUSDC:          string
  MockUSDT:          string
  MockOracle:        string
  TraderStake:       string
  InsuranceVault:    string
  FeeRouter:         string
  PerpetualExchange: string
  StrategyRegistry:  string
  CopyTracker:       string
  MockSwapRouter:    string
  ESGRegistry:       string
  KYCRegistry:       string
  PepeAMM:           string
  PepeToken:              string
  PepeClaim:              string
  EsgRewardDistributor:   string
  PepeIncentives:         string
  PepeStaking:            string
  AssetVault:             string
}

// ── Anvil local (chainId 31337) ───────────────────────────────────────────────
const ANVIL: ChainAddresses = {
  MockUSDC:          "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
  MockUSDT:          "0x0000000000000000000000000000000000000000",
  MockOracle:        "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
  TraderStake:       "0x0000000000000000000000000000000000000000",
  InsuranceVault:    "0x0000000000000000000000000000000000000000",
  FeeRouter:         "0x0000000000000000000000000000000000000000",
  PerpetualExchange: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
  StrategyRegistry:  "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
  CopyTracker:       "0x68B1D87F95878fE05B998F19b66F4baba5De1aed",
  MockSwapRouter:    "0x0000000000000000000000000000000000000000",
  ESGRegistry:       "0x0000000000000000000000000000000000000000",
  KYCRegistry:       "0x0000000000000000000000000000000000000000",
  PepeAMM:           "0x0000000000000000000000000000000000000000",
  PepeToken:              "0x0000000000000000000000000000000000000000",
  PepeClaim:              "0x0000000000000000000000000000000000000000",
  EsgRewardDistributor:   "0x0000000000000000000000000000000000000000",
  PepeIncentives:         "0x0000000000000000000000000000000000000000",
  PepeStaking:            "0x0000000000000000000000000000000000000000",
  AssetVault:             "0x0000000000000000000000000000000000000000",
}

// ── Sepolia testnet (chainId 11155111) — not supported in this repo ──────────
// Every Sepolia contract belongs to the original pepelab_onchain_cfd
// deployment. pepelab-colosseum must never send a transaction to it, so the
// chain is left out of CHAIN_MAP and the UI treats it as an unsupported network.

// ── Base Sepolia testnet (chainId 84532) ──────────────────────────────────────
// pepelab-colosseum's OWN deployment (Deploy.s.sol broadcast 2026-09-23 by
// 0xB98BA27B…3a02; broadcast/Deploy.s.sol/84532/run-latest.json). It shares
// nothing with the original pepelab_onchain_cfd deployment: every contract is
// new and no transaction was ever sent to an original-project address.
// Contracts not in Deploy.s.sol stay 0x0 → UI "not deployed" guards — they are
// deliberately NOT pointed at the original project's instances.
const BASE_SEPOLIA: ChainAddresses = {
  MockUSDC:          "0x0910e965B06845BD3871860d522952a44a574058",
  MockUSDT:          "0x0000000000000000000000000000000000000000",
  MockOracle:        "0x7c7FD43376738151a09719Ab5B33962a77dfBb49",
  TraderStake:       "0x790fd51ad485013C5b87FD7765679461675A31FD",
  InsuranceVault:    "0x42b9503E4AEf7A347DB75E54d32230720D1dd4f0",
  FeeRouter:         "0x91E4aC532201Fc67C715Aa202B6Fe85F51b34994",
  PerpetualExchange: "0xC45dEd77F4A30658e3c52E6fB4809E502e3D3B0E",
  StrategyRegistry:  "0x6Af6BEBC8fF0CE354e6E8A97921E1C5Ea95a7DE8",
  CopyTracker:       "0xF19E53dDBbD6CfDFb50deF952CA5f956ed08d0C4",
  MockSwapRouter:    "0xCebdae595260F31541E44FBFfC80614d8B73C87a",
  ESGRegistry:       "0x0000000000000000000000000000000000000000",
  KYCRegistry:       "0x34D644b9d58c1D4B0Cb805BA49440F53Ca0378d0",
  PepeAMM:           "0x0000000000000000000000000000000000000000",
  PepeToken:              "0x0000000000000000000000000000000000000000",
  PepeClaim:              "0x0000000000000000000000000000000000000000",
  EsgRewardDistributor:   "0x0000000000000000000000000000000000000000",
  PepeIncentives:         "0x0000000000000000000000000000000000000000",
  PepeStaking:            "0x0000000000000000000000000000000000000000",
  AssetVault:             "0x0000000000000000000000000000000000000000",
}

// Phase 4 production-oracle showcase on Base Sepolia (deployed, NOT wired into
// the live exchange — which runs on MockOracle so synthetic-asset demos work).
// AggregatorOracle fronts Chainlink + Pyth (Pyth live on Base Sepolia).
export const BASE_SEPOLIA_ORACLE_SHOWCASE = {
  ChainlinkAdapter: "0xb51Ab689348d5Ce69f6FB9dF45efe359e162964A",
  PythAdapter:      "0x2879d41C45135F87Ed92373F43b20446b07571Fd",
  AggregatorOracle: "0xE5903f1560Ed71Fd3A5a61a077DD9a8B0A963444",
} as const

// Exported (not just used internally) so callers that need "every chain's
// addresses" — e.g. assetMeta.ts building PEPE metadata for whichever chain
// the wallet is connected to — have one place to read from instead of
// re-hardcoding a chain's addresses a second time.
export const CHAIN_MAP: Record<number, ChainAddresses> = {
  31337:    ANVIL,
  84532:    BASE_SEPOLIA,
}

export const getAddresses = (chainId: number | null): ChainAddresses | null =>
  chainId === null ? null : (CHAIN_MAP[chainId] ?? null)

export const CHAIN_NAMES: Record<number, string> = {
  31337:    'Anvil Local',
  11155111: 'Sepolia（legacy demo）',
  84532:    'Base Sepolia',
}

/**
 * 正式部署鏈。交易引擎、agent session、x402 收費全部只在這裡。
 *
 * 不是偏好問題，是限制：x402 的 `exact` scheme 需要 Circle 官方 USDC 走
 * EIP-3009 `transferWithAuthorization`（`0x036CbD53…CF7e`），那顆幣只有 Base
 * Sepolia 有。所以只要產品包含 x402，Base 就是唯一可能的鏈。
 */
export const PRIMARY_CHAIN_ID = 84532

/**
 * 2026-08-07：Base 的六個缺口（MockUSDT / ESGRegistry / PepeClaim /
 * EsgRewardDistributor / PepeStaking / AssetVault + 11 顆 SyntheticAsset）
 * 已補齊並註冊，所以「canonical 鏈缺代幣化資產」這個矛盾消失了。
 * Base 現在是唯一一條完整的鏈：交易、agent session、x402、代幣化資產都在。
 *
 * Sepolia 仍然部署著、仍然可讀，但它只剩一項 Base 沒有的東西：V2 硬化金庫
 * （V2_STACK）。那是一組對照展示，不是產品路徑。
 *
 * 兩條鏈仍然不是彼此的鏡像，所以 UI 必須說清楚使用者現在站在哪一邊，
 * 而不是靜默地讓半個產品消失。
 */
export const isPrimaryChain = (chainId: number | null): boolean =>
  chainId === PRIMARY_CHAIN_ID


// keccak256 of symbol string — matches Deploy.s.sol and on-chain IDs
export const ASSET_IDS = {
  sBTC:   "0x6587d61b59ac1e9c9f12c71f220fb1b1740d054e81277d4466a0d348e0e266e1" as `0x${string}`,
  sETH:   "0x83e22e1d95f2093dd401ec5cba75bcd950cd90282356f086011849e4fbaad8a9"  as `0x${string}`,
  sAAPL:  "0xeed17252f75eebef59a2839f0991464677fec970326e35128ddaf7f3acfb7220"  as `0x${string}`,
  sTSLA:  "0xd3cea6476633c192bfd36c9af4a9d0ee6e1863484325ee0f546a36393d1df1e9"  as `0x${string}`,
  sGOLD:  "0x12b611f69af3b5e84f9d2d8a8818b4ad7f2cf0b45274bc7c3b9616f67c7baa1a" as `0x${string}`,
  sBOND:  "0xc310184149786e37d3493804e896dd8582e216011114ff6a7b6b8c02678bf6bb"  as `0x${string}`,
  sNVDA:  "0x59367feafbd2791db3a7462e596e9514b8f32a0dd24dcb4fd34af4725e59388d" as `0x${string}`,
  sMSFT:  "0x9148a0fa033f72a846b348bb77b949e9dde2f4cd70a6045eb9e25ee5215b5b0b" as `0x${string}`,
  sGOOGL: "0xa0934421d87a4a6d14ebffa8df8f7aeda1ab515b1a348ca82620b23a527b6875" as `0x${string}`,
  sICLN:  "0x61663214831fdd7b1dd003226fb7436774c5b030f5858cf47d7aee23934564cb" as `0x${string}`,
  sESGU:  "0x5820b70264a0c106d7ef7036e13c03b5d9018e2b51178ed68526cf915d594ca2" as `0x${string}`,
} as const

// Initial oracle prices (8-decimal, same as MockOracle storage)
export const INITIAL_PRICES: Partial<Record<keyof typeof ASSET_IDS, bigint>> = {
  sBTC:   50_000n * 10n ** 8n,
  sETH:    3_000n * 10n ** 8n,
  sAAPL:     200n * 10n ** 8n,
  sTSLA:     250n * 10n ** 8n,
  sGOLD:   2_650n * 10n ** 8n,
  sBOND:      48n * 10n ** 8n,  // #106: now tracks BGRN (green bond ETF), ~$48; was TLT ~$100
  sNVDA:     135n * 10n ** 8n,
  sMSFT:     420n * 10n ** 8n,
  sGOOGL:    175n * 10n ** 8n,
  sICLN:      14n * 10n ** 8n,
  sESGU:     120n * 10n ** 8n,
}

export type ContractName = keyof typeof ANVIL
export type AssetSymbol  = keyof typeof ASSET_IDS

// ── Tokenized assets (ERC-20 wrapper layer) ───────────────────────────────────
// SyntheticAsset addresses per chain, filled in after DeploySyntheticAssets.
// Empty = the tokenized layer is not live on that chain; the /tokens page shows
// a "not enabled yet" notice instead of failing.
export const SYNTH_TOKENS: Record<number, Partial<Record<AssetSymbol, string>>> = {
  31337:    {},
  // pepelab-colosseum has not deployed the tokenized layer on Base Sepolia;
  // the original project's SyntheticAssets are intentionally not listed here.
  84532: {},
}

export const getSynthTokens = (
  chainId: number | null,
): Partial<Record<AssetSymbol, string>> =>
  chainId === null ? {} : (SYNTH_TOKENS[chainId] ?? {})

// ── V2 hardened stack ────────────────────────────────────────────────────────
// Runs ALONGSIDE V1, which stays deployed and untouched. Differences that matter:
//   - GuardedOracle replaces MockOracle's single owner key with N keepers plus a
//     per-update deviation cap, freeze, and pause. Verified on chain: a post of
//     $1 against a $200 price reverts DeviationTooLarge; a 3% move is accepted.
//   - AssetVaultV2 is a UUPS proxy whose oracle is ordinary storage, so it can
//     be repointed with setOracle — the exchange cannot, its oracle is immutable.
//   - SafeERC20, reentrancy guards, per-asset caps, and a reserve-ratio gate.
//   - V2.4 (#128, ADR-006): the mint fee is per-asset, derived from the asset's
//     WITNESSED carbon tier via ESGRegistryV2.medianCarbonTier. `ESGRegistryV2`
//     and `SustainabilityBadge` are part of this stack from #129 onward.
// See docs/RISK_MODEL.md, docs/KNOWN_LIMITATIONS.md, docs/DEPLOY_129_CUTOVER.md.
export const V2_STACK: Record<number, {
  GuardedOracle:        string
  AssetVaultV2:         string
  /** #128/#129 — carbon-tier attestation registry (medianCarbonTier). */
  ESGRegistryV2?:       string
  /** #98/#129 — non-transferable achievement token minted by EsgRewardDistributor. */
  SustainabilityBadge?: string
  tokens: Partial<Record<AssetSymbol, string>>
}> = {
  // Base Sepolia (84532): pepelab-colosseum has no hardened stack deployed.
  // The original project's V2 contracts are intentionally not listed here, so
  // hasV2Stack(84532) is false and the UI renders its "not deployed" path.
}

export const getV2Stack = (chainId: number | null) =>
  chainId === null ? undefined : V2_STACK[chainId]

/** True once a chain's hardened stack has real (non-zero) core addresses. */
export const hasV2Stack = (chainId: number | null): boolean => {
  const s = getV2Stack(chainId)
  const ZERO = "0x0000000000000000000000000000000000000000"
  return !!s && s.GuardedOracle !== ZERO && s.AssetVaultV2 !== ZERO
}
